services:
  db:
    container_name: ProtectKids_db
    image: postgres:15
    environment:
      - POSTGRES_USER=augusto
      - POSTGRES_PASSWORD=squad10
      - POSTGRES_DB=legislativo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U augusto -d legislativo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: ProtectKids_backend
    image: ghcr.io/unb-mds/2026-1-protectkids-backend:latest
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://augusto:squad10@db:5432/legislativo_db

  frontend:
    build: ./frontend
    container_name: ProtectKids_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  postgres_data:
