site_name: ProtectKids
site_url: https://unb-mds.github.io/2026-1-ProtectKids/
nav:
  - Início: index.md
  - Visão Geral: visao-geral.md
  - Requisitos: requisitos.md
  - Arquitetura: arquitetura.md
  - Contribuição: contribuicao.md

theme:
  name: material

  palette:
    - scheme: default
      primary: custom
      accent: custom

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

markdown_extensions:
  - toc:
      permalink: true

extra_css:
  - stylesheets/extra.css