site_name: ProtectKids
site_url: https://unb-mds.github.io/2026-1-ProtectKids/

nav:
  - Início: index.md
  - Visão Geral: visao-geral.md
  - Requisitos: requisitos.md
  - Arquitetura: arquitetura.md

  - Infraestrutura:
      - Docker Compose: infra/dockercompose.md

  - Contribuição: contribuicao.md

theme:
  name: material

  language: pt-BR

  palette:
    - scheme: default
      primary: custom
      accent: custom

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - toc.integrate
    - content.code.copy
    - search.highlight
    - search.suggest

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite

extra_css:
  - stylesheets/extra.css
